apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-brukernotifikasjonbestiller
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: dittnav-brukernotifikasjonbestiller-secrets
    - secret: influxdb-credentials
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 30
  readiness:
    path: /internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  webproxy: true
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "100m"
      memory: 400Mi
  gcp:
    sqlInstances:
      - name: brukernotifikasjonbestiller
        type: POSTGRES_11
        tier: db-custom-2-12288
        diskType: SSD
        highAvailability: true
        diskSize: 100
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: brukernotifikasjonbestiller
            envVarPrefix: DB
        maintenanceWindow:
          day: 1
          hour: 4
        cascadingDelete: false
  kafka:
    pool: nav-prod
  accessPolicy:
    outbound:
      external:
        - host: kafka-schema-registry.nais.adeo.no
        - host: dittnav-event-handler.nais.oera.no

