apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-brukernotifikasjonbestiller
  namespace: personbruker
  labels:
    team: personbruker
spec:
  envFrom:
    - secret: dittnav-brukernotifikasjonbestiller-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  webproxy: true
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 580Mi
  gcp:
    sqlInstances:
      - name: brukernotifikasjonbestiller
        type: POSTGRES_11
        tier: db-f1-micro
        diskType: SSD
        diskSize: 10
        diskAutoresize: false
        autoBackupTime: "03:00"
        databases:
          - name: brukernotifikasjonbestiller
            envVarPrefix: DB
        maintenanceWindow:
          day: 1
          hour: 4
        cascadingDelete: false
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      external:
        - host: kafka-schema-registry.nais-q.adeo.no

